// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/vgmdj/ddd-case/infrastructure/repository/ent/schema"
	"github.com/vgmdj/ddd-case/infrastructure/repository/ent/skuaction"
	"github.com/vgmdj/ddd-case/infrastructure/repository/ent/skuconfig"
	"github.com/vgmdj/ddd-case/infrastructure/repository/ent/skustatuscode"
	"github.com/vgmdj/ddd-case/infrastructure/repository/ent/skutemplate"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	skuactionFields := schema.SkuAction{}.Fields()
	_ = skuactionFields
	// skuactionDescCreateAt is the schema descriptor for create_at field.
	skuactionDescCreateAt := skuactionFields[5].Descriptor()
	// skuaction.DefaultCreateAt holds the default value on creation for the create_at field.
	skuaction.DefaultCreateAt = skuactionDescCreateAt.Default.(func() time.Time)
	// skuactionDescUpdateAt is the schema descriptor for update_at field.
	skuactionDescUpdateAt := skuactionFields[6].Descriptor()
	// skuaction.DefaultUpdateAt holds the default value on creation for the update_at field.
	skuaction.DefaultUpdateAt = skuactionDescUpdateAt.Default.(func() time.Time)
	// skuaction.UpdateDefaultUpdateAt holds the default value on update for the update_at field.
	skuaction.UpdateDefaultUpdateAt = skuactionDescUpdateAt.UpdateDefault.(func() time.Time)
	skuconfigFields := schema.SkuConfig{}.Fields()
	_ = skuconfigFields
	// skuconfigDescCreateAt is the schema descriptor for create_at field.
	skuconfigDescCreateAt := skuconfigFields[2].Descriptor()
	// skuconfig.DefaultCreateAt holds the default value on creation for the create_at field.
	skuconfig.DefaultCreateAt = skuconfigDescCreateAt.Default.(func() time.Time)
	// skuconfigDescUpdateAt is the schema descriptor for update_at field.
	skuconfigDescUpdateAt := skuconfigFields[3].Descriptor()
	// skuconfig.DefaultUpdateAt holds the default value on creation for the update_at field.
	skuconfig.DefaultUpdateAt = skuconfigDescUpdateAt.Default.(func() time.Time)
	// skuconfig.UpdateDefaultUpdateAt holds the default value on update for the update_at field.
	skuconfig.UpdateDefaultUpdateAt = skuconfigDescUpdateAt.UpdateDefault.(func() time.Time)
	skustatuscodeFields := schema.SkuStatusCode{}.Fields()
	_ = skustatuscodeFields
	// skustatuscodeDescCreateAt is the schema descriptor for create_at field.
	skustatuscodeDescCreateAt := skustatuscodeFields[3].Descriptor()
	// skustatuscode.DefaultCreateAt holds the default value on creation for the create_at field.
	skustatuscode.DefaultCreateAt = skustatuscodeDescCreateAt.Default.(func() time.Time)
	// skustatuscodeDescUpdateAt is the schema descriptor for update_at field.
	skustatuscodeDescUpdateAt := skustatuscodeFields[4].Descriptor()
	// skustatuscode.DefaultUpdateAt holds the default value on creation for the update_at field.
	skustatuscode.DefaultUpdateAt = skustatuscodeDescUpdateAt.Default.(func() time.Time)
	// skustatuscode.UpdateDefaultUpdateAt holds the default value on update for the update_at field.
	skustatuscode.UpdateDefaultUpdateAt = skustatuscodeDescUpdateAt.UpdateDefault.(func() time.Time)
	skutemplateFields := schema.SkuTemplate{}.Fields()
	_ = skutemplateFields
	// skutemplateDescCreateAt is the schema descriptor for create_at field.
	skutemplateDescCreateAt := skutemplateFields[3].Descriptor()
	// skutemplate.DefaultCreateAt holds the default value on creation for the create_at field.
	skutemplate.DefaultCreateAt = skutemplateDescCreateAt.Default.(func() time.Time)
	// skutemplateDescUpdateAt is the schema descriptor for update_at field.
	skutemplateDescUpdateAt := skutemplateFields[4].Descriptor()
	// skutemplate.DefaultUpdateAt holds the default value on creation for the update_at field.
	skutemplate.DefaultUpdateAt = skutemplateDescUpdateAt.Default.(func() time.Time)
	// skutemplate.UpdateDefaultUpdateAt holds the default value on update for the update_at field.
	skutemplate.UpdateDefaultUpdateAt = skutemplateDescUpdateAt.UpdateDefault.(func() time.Time)
}
