// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/vgmdj/ddd-case/infrastructure/repository/ent/predicate"
	"github.com/vgmdj/ddd-case/infrastructure/repository/ent/skuaction"
)

// SkuActionDelete is the builder for deleting a SkuAction entity.
type SkuActionDelete struct {
	config
	hooks    []Hook
	mutation *SkuActionMutation
}

// Where adds a new predicate to the delete builder.
func (sad *SkuActionDelete) Where(ps ...predicate.SkuAction) *SkuActionDelete {
	sad.mutation.predicates = append(sad.mutation.predicates, ps...)
	return sad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sad *SkuActionDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(sad.hooks) == 0 {
		affected, err = sad.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SkuActionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sad.mutation = mutation
			affected, err = sad.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(sad.hooks) - 1; i >= 0; i-- {
			mut = sad.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sad.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (sad *SkuActionDelete) ExecX(ctx context.Context) int {
	n, err := sad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sad *SkuActionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: skuaction.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: skuaction.FieldID,
			},
		},
	}
	if ps := sad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, sad.driver, _spec)
}

// SkuActionDeleteOne is the builder for deleting a single SkuAction entity.
type SkuActionDeleteOne struct {
	sad *SkuActionDelete
}

// Exec executes the deletion query.
func (sado *SkuActionDeleteOne) Exec(ctx context.Context) error {
	n, err := sado.sad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{skuaction.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sado *SkuActionDeleteOne) ExecX(ctx context.Context) {
	sado.sad.ExecX(ctx)
}
