// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/vgmdj/ddd-case/infrastructure/repository/ent/predicate"
	"github.com/vgmdj/ddd-case/infrastructure/repository/ent/skuaction"
	"github.com/vgmdj/ddd-case/infrastructure/repository/ent/skuconfig"
)

// SkuConfigQuery is the builder for querying SkuConfig entities.
type SkuConfigQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	predicates []predicate.SkuConfig
	// eager-loading edges.
	withAction *SkuActionQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (scq *SkuConfigQuery) Where(ps ...predicate.SkuConfig) *SkuConfigQuery {
	scq.predicates = append(scq.predicates, ps...)
	return scq
}

// Limit adds a limit step to the query.
func (scq *SkuConfigQuery) Limit(limit int) *SkuConfigQuery {
	scq.limit = &limit
	return scq
}

// Offset adds an offset step to the query.
func (scq *SkuConfigQuery) Offset(offset int) *SkuConfigQuery {
	scq.offset = &offset
	return scq
}

// Order adds an order step to the query.
func (scq *SkuConfigQuery) Order(o ...OrderFunc) *SkuConfigQuery {
	scq.order = append(scq.order, o...)
	return scq
}

// QueryAction chains the current query on the action edge.
func (scq *SkuConfigQuery) QueryAction() *SkuActionQuery {
	query := &SkuActionQuery{config: scq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := scq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := scq.sqlQuery()
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(skuconfig.Table, skuconfig.FieldID, selector),
			sqlgraph.To(skuaction.Table, skuaction.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, skuconfig.ActionTable, skuconfig.ActionColumn),
		)
		fromU = sqlgraph.SetNeighbors(scq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SkuConfig entity in the query. Returns *NotFoundError when no skuconfig was found.
func (scq *SkuConfigQuery) First(ctx context.Context) (*SkuConfig, error) {
	nodes, err := scq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{skuconfig.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (scq *SkuConfigQuery) FirstX(ctx context.Context) *SkuConfig {
	node, err := scq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SkuConfig id in the query. Returns *NotFoundError when no id was found.
func (scq *SkuConfigQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = scq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{skuconfig.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (scq *SkuConfigQuery) FirstIDX(ctx context.Context) int {
	id, err := scq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only SkuConfig entity in the query, returns an error if not exactly one entity was returned.
func (scq *SkuConfigQuery) Only(ctx context.Context) (*SkuConfig, error) {
	nodes, err := scq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{skuconfig.Label}
	default:
		return nil, &NotSingularError{skuconfig.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (scq *SkuConfigQuery) OnlyX(ctx context.Context) *SkuConfig {
	node, err := scq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID returns the only SkuConfig id in the query, returns an error if not exactly one id was returned.
func (scq *SkuConfigQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = scq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{skuconfig.Label}
	default:
		err = &NotSingularError{skuconfig.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (scq *SkuConfigQuery) OnlyIDX(ctx context.Context) int {
	id, err := scq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SkuConfigs.
func (scq *SkuConfigQuery) All(ctx context.Context) ([]*SkuConfig, error) {
	if err := scq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return scq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (scq *SkuConfigQuery) AllX(ctx context.Context) []*SkuConfig {
	nodes, err := scq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SkuConfig ids.
func (scq *SkuConfigQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := scq.Select(skuconfig.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (scq *SkuConfigQuery) IDsX(ctx context.Context) []int {
	ids, err := scq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (scq *SkuConfigQuery) Count(ctx context.Context) (int, error) {
	if err := scq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return scq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (scq *SkuConfigQuery) CountX(ctx context.Context) int {
	count, err := scq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (scq *SkuConfigQuery) Exist(ctx context.Context) (bool, error) {
	if err := scq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return scq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (scq *SkuConfigQuery) ExistX(ctx context.Context) bool {
	exist, err := scq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (scq *SkuConfigQuery) Clone() *SkuConfigQuery {
	if scq == nil {
		return nil
	}
	return &SkuConfigQuery{
		config:     scq.config,
		limit:      scq.limit,
		offset:     scq.offset,
		order:      append([]OrderFunc{}, scq.order...),
		predicates: append([]predicate.SkuConfig{}, scq.predicates...),
		withAction: scq.withAction.Clone(),
		// clone intermediate query.
		sql:  scq.sql.Clone(),
		path: scq.path,
	}
}

//  WithAction tells the query-builder to eager-loads the nodes that are connected to
// the "action" edge. The optional arguments used to configure the query builder of the edge.
func (scq *SkuConfigQuery) WithAction(opts ...func(*SkuActionQuery)) *SkuConfigQuery {
	query := &SkuActionQuery{config: scq.config}
	for _, opt := range opts {
		opt(query)
	}
	scq.withAction = query
	return scq
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Config string `json:"config,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SkuConfig.Query().
//		GroupBy(skuconfig.FieldConfig).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (scq *SkuConfigQuery) GroupBy(field string, fields ...string) *SkuConfigGroupBy {
	group := &SkuConfigGroupBy{config: scq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := scq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return scq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		Config string `json:"config,omitempty"`
//	}
//
//	client.SkuConfig.Query().
//		Select(skuconfig.FieldConfig).
//		Scan(ctx, &v)
//
func (scq *SkuConfigQuery) Select(field string, fields ...string) *SkuConfigSelect {
	selector := &SkuConfigSelect{config: scq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := scq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return scq.sqlQuery(), nil
	}
	return selector
}

func (scq *SkuConfigQuery) prepareQuery(ctx context.Context) error {
	if scq.path != nil {
		prev, err := scq.path(ctx)
		if err != nil {
			return err
		}
		scq.sql = prev
	}
	return nil
}

func (scq *SkuConfigQuery) sqlAll(ctx context.Context) ([]*SkuConfig, error) {
	var (
		nodes       = []*SkuConfig{}
		withFKs     = scq.withFKs
		_spec       = scq.querySpec()
		loadedTypes = [1]bool{
			scq.withAction != nil,
		}
	)
	if scq.withAction != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, skuconfig.ForeignKeys...)
	}
	_spec.ScanValues = func() []interface{} {
		node := &SkuConfig{config: scq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		if withFKs {
			values = append(values, node.fkValues()...)
		}
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, scq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := scq.withAction; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*SkuConfig)
		for i := range nodes {
			if fk := nodes[i].sku_action_id; fk != nil {
				ids = append(ids, *fk)
				nodeids[*fk] = append(nodeids[*fk], nodes[i])
			}
		}
		query.Where(skuaction.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "sku_action_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Action = n
			}
		}
	}

	return nodes, nil
}

func (scq *SkuConfigQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := scq.querySpec()
	return sqlgraph.CountNodes(ctx, scq.driver, _spec)
}

func (scq *SkuConfigQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := scq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (scq *SkuConfigQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   skuconfig.Table,
			Columns: skuconfig.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: skuconfig.FieldID,
			},
		},
		From:   scq.sql,
		Unique: true,
	}
	if ps := scq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := scq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := scq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := scq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, skuconfig.ValidColumn)
			}
		}
	}
	return _spec
}

func (scq *SkuConfigQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(scq.driver.Dialect())
	t1 := builder.Table(skuconfig.Table)
	selector := builder.Select(t1.Columns(skuconfig.Columns...)...).From(t1)
	if scq.sql != nil {
		selector = scq.sql
		selector.Select(selector.Columns(skuconfig.Columns...)...)
	}
	for _, p := range scq.predicates {
		p(selector)
	}
	for _, p := range scq.order {
		p(selector, skuconfig.ValidColumn)
	}
	if offset := scq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := scq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SkuConfigGroupBy is the builder for group-by SkuConfig entities.
type SkuConfigGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (scgb *SkuConfigGroupBy) Aggregate(fns ...AggregateFunc) *SkuConfigGroupBy {
	scgb.fns = append(scgb.fns, fns...)
	return scgb
}

// Scan applies the group-by query and scan the result into the given value.
func (scgb *SkuConfigGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := scgb.path(ctx)
	if err != nil {
		return err
	}
	scgb.sql = query
	return scgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (scgb *SkuConfigGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := scgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (scgb *SkuConfigGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(scgb.fields) > 1 {
		return nil, errors.New("ent: SkuConfigGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := scgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (scgb *SkuConfigGroupBy) StringsX(ctx context.Context) []string {
	v, err := scgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (scgb *SkuConfigGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = scgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{skuconfig.Label}
	default:
		err = fmt.Errorf("ent: SkuConfigGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (scgb *SkuConfigGroupBy) StringX(ctx context.Context) string {
	v, err := scgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (scgb *SkuConfigGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(scgb.fields) > 1 {
		return nil, errors.New("ent: SkuConfigGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := scgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (scgb *SkuConfigGroupBy) IntsX(ctx context.Context) []int {
	v, err := scgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (scgb *SkuConfigGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = scgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{skuconfig.Label}
	default:
		err = fmt.Errorf("ent: SkuConfigGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (scgb *SkuConfigGroupBy) IntX(ctx context.Context) int {
	v, err := scgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (scgb *SkuConfigGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(scgb.fields) > 1 {
		return nil, errors.New("ent: SkuConfigGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := scgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (scgb *SkuConfigGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := scgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (scgb *SkuConfigGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = scgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{skuconfig.Label}
	default:
		err = fmt.Errorf("ent: SkuConfigGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (scgb *SkuConfigGroupBy) Float64X(ctx context.Context) float64 {
	v, err := scgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (scgb *SkuConfigGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(scgb.fields) > 1 {
		return nil, errors.New("ent: SkuConfigGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := scgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (scgb *SkuConfigGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := scgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (scgb *SkuConfigGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = scgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{skuconfig.Label}
	default:
		err = fmt.Errorf("ent: SkuConfigGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (scgb *SkuConfigGroupBy) BoolX(ctx context.Context) bool {
	v, err := scgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (scgb *SkuConfigGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range scgb.fields {
		if !skuconfig.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := scgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := scgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (scgb *SkuConfigGroupBy) sqlQuery() *sql.Selector {
	selector := scgb.sql
	columns := make([]string, 0, len(scgb.fields)+len(scgb.fns))
	columns = append(columns, scgb.fields...)
	for _, fn := range scgb.fns {
		columns = append(columns, fn(selector, skuconfig.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(scgb.fields...)
}

// SkuConfigSelect is the builder for select fields of SkuConfig entities.
type SkuConfigSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (scs *SkuConfigSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := scs.path(ctx)
	if err != nil {
		return err
	}
	scs.sql = query
	return scs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (scs *SkuConfigSelect) ScanX(ctx context.Context, v interface{}) {
	if err := scs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (scs *SkuConfigSelect) Strings(ctx context.Context) ([]string, error) {
	if len(scs.fields) > 1 {
		return nil, errors.New("ent: SkuConfigSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := scs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (scs *SkuConfigSelect) StringsX(ctx context.Context) []string {
	v, err := scs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (scs *SkuConfigSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = scs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{skuconfig.Label}
	default:
		err = fmt.Errorf("ent: SkuConfigSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (scs *SkuConfigSelect) StringX(ctx context.Context) string {
	v, err := scs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (scs *SkuConfigSelect) Ints(ctx context.Context) ([]int, error) {
	if len(scs.fields) > 1 {
		return nil, errors.New("ent: SkuConfigSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := scs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (scs *SkuConfigSelect) IntsX(ctx context.Context) []int {
	v, err := scs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (scs *SkuConfigSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = scs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{skuconfig.Label}
	default:
		err = fmt.Errorf("ent: SkuConfigSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (scs *SkuConfigSelect) IntX(ctx context.Context) int {
	v, err := scs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (scs *SkuConfigSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(scs.fields) > 1 {
		return nil, errors.New("ent: SkuConfigSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := scs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (scs *SkuConfigSelect) Float64sX(ctx context.Context) []float64 {
	v, err := scs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (scs *SkuConfigSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = scs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{skuconfig.Label}
	default:
		err = fmt.Errorf("ent: SkuConfigSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (scs *SkuConfigSelect) Float64X(ctx context.Context) float64 {
	v, err := scs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (scs *SkuConfigSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(scs.fields) > 1 {
		return nil, errors.New("ent: SkuConfigSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := scs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (scs *SkuConfigSelect) BoolsX(ctx context.Context) []bool {
	v, err := scs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (scs *SkuConfigSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = scs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{skuconfig.Label}
	default:
		err = fmt.Errorf("ent: SkuConfigSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (scs *SkuConfigSelect) BoolX(ctx context.Context) bool {
	v, err := scs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (scs *SkuConfigSelect) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range scs.fields {
		if !skuconfig.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for selection", f)}
		}
	}
	rows := &sql.Rows{}
	query, args := scs.sqlQuery().Query()
	if err := scs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (scs *SkuConfigSelect) sqlQuery() sql.Querier {
	selector := scs.sql
	selector.Select(selector.Columns(scs.fields...)...)
	return selector
}
