// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/vgmdj/ddd-case/infrastructure/repository/ent/predicate"
	"github.com/vgmdj/ddd-case/infrastructure/repository/ent/skustatuscode"
)

// SkuStatusCodeDelete is the builder for deleting a SkuStatusCode entity.
type SkuStatusCodeDelete struct {
	config
	hooks    []Hook
	mutation *SkuStatusCodeMutation
}

// Where adds a new predicate to the delete builder.
func (sscd *SkuStatusCodeDelete) Where(ps ...predicate.SkuStatusCode) *SkuStatusCodeDelete {
	sscd.mutation.predicates = append(sscd.mutation.predicates, ps...)
	return sscd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sscd *SkuStatusCodeDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(sscd.hooks) == 0 {
		affected, err = sscd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SkuStatusCodeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sscd.mutation = mutation
			affected, err = sscd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(sscd.hooks) - 1; i >= 0; i-- {
			mut = sscd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sscd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (sscd *SkuStatusCodeDelete) ExecX(ctx context.Context) int {
	n, err := sscd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sscd *SkuStatusCodeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: skustatuscode.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: skustatuscode.FieldID,
			},
		},
	}
	if ps := sscd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, sscd.driver, _spec)
}

// SkuStatusCodeDeleteOne is the builder for deleting a single SkuStatusCode entity.
type SkuStatusCodeDeleteOne struct {
	sscd *SkuStatusCodeDelete
}

// Exec executes the deletion query.
func (sscdo *SkuStatusCodeDeleteOne) Exec(ctx context.Context) error {
	n, err := sscdo.sscd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{skustatuscode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sscdo *SkuStatusCodeDeleteOne) ExecX(ctx context.Context) {
	sscdo.sscd.ExecX(ctx)
}
