// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/vgmdj/ddd-case/infrastructure/repository/ent/skuaction"
	"github.com/vgmdj/ddd-case/infrastructure/repository/ent/skutemplate"
)

// SkuTemplateCreate is the builder for creating a SkuTemplate entity.
type SkuTemplateCreate struct {
	config
	mutation *SkuTemplateMutation
	hooks    []Hook
}

// SetRequest sets the request field.
func (stc *SkuTemplateCreate) SetRequest(s string) *SkuTemplateCreate {
	stc.mutation.SetRequest(s)
	return stc
}

// SetResponse sets the response field.
func (stc *SkuTemplateCreate) SetResponse(s string) *SkuTemplateCreate {
	stc.mutation.SetResponse(s)
	return stc
}

// SetStatus sets the status field.
func (stc *SkuTemplateCreate) SetStatus(i int) *SkuTemplateCreate {
	stc.mutation.SetStatus(i)
	return stc
}

// SetCreateAt sets the create_at field.
func (stc *SkuTemplateCreate) SetCreateAt(t time.Time) *SkuTemplateCreate {
	stc.mutation.SetCreateAt(t)
	return stc
}

// SetNillableCreateAt sets the create_at field if the given value is not nil.
func (stc *SkuTemplateCreate) SetNillableCreateAt(t *time.Time) *SkuTemplateCreate {
	if t != nil {
		stc.SetCreateAt(*t)
	}
	return stc
}

// SetUpdateAt sets the update_at field.
func (stc *SkuTemplateCreate) SetUpdateAt(t time.Time) *SkuTemplateCreate {
	stc.mutation.SetUpdateAt(t)
	return stc
}

// SetNillableUpdateAt sets the update_at field if the given value is not nil.
func (stc *SkuTemplateCreate) SetNillableUpdateAt(t *time.Time) *SkuTemplateCreate {
	if t != nil {
		stc.SetUpdateAt(*t)
	}
	return stc
}

// SetActionID sets the action edge to SkuAction by id.
func (stc *SkuTemplateCreate) SetActionID(id int) *SkuTemplateCreate {
	stc.mutation.SetActionID(id)
	return stc
}

// SetNillableActionID sets the action edge to SkuAction by id if the given value is not nil.
func (stc *SkuTemplateCreate) SetNillableActionID(id *int) *SkuTemplateCreate {
	if id != nil {
		stc = stc.SetActionID(*id)
	}
	return stc
}

// SetAction sets the action edge to SkuAction.
func (stc *SkuTemplateCreate) SetAction(s *SkuAction) *SkuTemplateCreate {
	return stc.SetActionID(s.ID)
}

// Mutation returns the SkuTemplateMutation object of the builder.
func (stc *SkuTemplateCreate) Mutation() *SkuTemplateMutation {
	return stc.mutation
}

// Save creates the SkuTemplate in the database.
func (stc *SkuTemplateCreate) Save(ctx context.Context) (*SkuTemplate, error) {
	var (
		err  error
		node *SkuTemplate
	)
	stc.defaults()
	if len(stc.hooks) == 0 {
		if err = stc.check(); err != nil {
			return nil, err
		}
		node, err = stc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SkuTemplateMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = stc.check(); err != nil {
				return nil, err
			}
			stc.mutation = mutation
			node, err = stc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(stc.hooks) - 1; i >= 0; i-- {
			mut = stc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, stc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (stc *SkuTemplateCreate) SaveX(ctx context.Context) *SkuTemplate {
	v, err := stc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (stc *SkuTemplateCreate) defaults() {
	if _, ok := stc.mutation.CreateAt(); !ok {
		v := skutemplate.DefaultCreateAt()
		stc.mutation.SetCreateAt(v)
	}
	if _, ok := stc.mutation.UpdateAt(); !ok {
		v := skutemplate.DefaultUpdateAt()
		stc.mutation.SetUpdateAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (stc *SkuTemplateCreate) check() error {
	if _, ok := stc.mutation.Request(); !ok {
		return &ValidationError{Name: "request", err: errors.New("ent: missing required field \"request\"")}
	}
	if _, ok := stc.mutation.Response(); !ok {
		return &ValidationError{Name: "response", err: errors.New("ent: missing required field \"response\"")}
	}
	if _, ok := stc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New("ent: missing required field \"status\"")}
	}
	if _, ok := stc.mutation.CreateAt(); !ok {
		return &ValidationError{Name: "create_at", err: errors.New("ent: missing required field \"create_at\"")}
	}
	if _, ok := stc.mutation.UpdateAt(); !ok {
		return &ValidationError{Name: "update_at", err: errors.New("ent: missing required field \"update_at\"")}
	}
	return nil
}

func (stc *SkuTemplateCreate) sqlSave(ctx context.Context) (*SkuTemplate, error) {
	_node, _spec := stc.createSpec()
	if err := sqlgraph.CreateNode(ctx, stc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (stc *SkuTemplateCreate) createSpec() (*SkuTemplate, *sqlgraph.CreateSpec) {
	var (
		_node = &SkuTemplate{config: stc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: skutemplate.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: skutemplate.FieldID,
			},
		}
	)
	if value, ok := stc.mutation.Request(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: skutemplate.FieldRequest,
		})
		_node.Request = value
	}
	if value, ok := stc.mutation.Response(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: skutemplate.FieldResponse,
		})
		_node.Response = value
	}
	if value, ok := stc.mutation.Status(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: skutemplate.FieldStatus,
		})
		_node.Status = value
	}
	if value, ok := stc.mutation.CreateAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: skutemplate.FieldCreateAt,
		})
		_node.CreateAt = value
	}
	if value, ok := stc.mutation.UpdateAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: skutemplate.FieldUpdateAt,
		})
		_node.UpdateAt = value
	}
	if nodes := stc.mutation.ActionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   skutemplate.ActionTable,
			Columns: []string{skutemplate.ActionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: skuaction.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SkuTemplateCreateBulk is the builder for creating a bulk of SkuTemplate entities.
type SkuTemplateCreateBulk struct {
	config
	builders []*SkuTemplateCreate
}

// Save creates the SkuTemplate entities in the database.
func (stcb *SkuTemplateCreateBulk) Save(ctx context.Context) ([]*SkuTemplate, error) {
	specs := make([]*sqlgraph.CreateSpec, len(stcb.builders))
	nodes := make([]*SkuTemplate, len(stcb.builders))
	mutators := make([]Mutator, len(stcb.builders))
	for i := range stcb.builders {
		func(i int, root context.Context) {
			builder := stcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SkuTemplateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, stcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, stcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, stcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX calls Save and panics if Save returns an error.
func (stcb *SkuTemplateCreateBulk) SaveX(ctx context.Context) []*SkuTemplate {
	v, err := stcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
