// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// SkuAction is the predicate function for skuaction builders.
type SkuAction func(*sql.Selector)

// SkuConfig is the predicate function for skuconfig builders.
type SkuConfig func(*sql.Selector)

// SkuStatusCode is the predicate function for skustatuscode builders.
type SkuStatusCode func(*sql.Selector)

// SkuTemplate is the predicate function for skutemplate builders.
type SkuTemplate func(*sql.Selector)
