// Code generated by entc, DO NOT EDIT.

package skustatuscode

import (
	"time"
)

const (
	// Label holds the string label denoting the skustatuscode type in the database.
	Label = "sku_status_code"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInsuranceCode holds the string denoting the insurance_code field in the database.
	FieldInsuranceCode = "insurance_code"
	// FieldReflectCode holds the string denoting the reflect_code field in the database.
	FieldReflectCode = "reflect_code"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreateAt holds the string denoting the create_at field in the database.
	FieldCreateAt = "create_at"
	// FieldUpdateAt holds the string denoting the update_at field in the database.
	FieldUpdateAt = "update_at"

	// EdgeAction holds the string denoting the action edge name in mutations.
	EdgeAction = "action"

	// Table holds the table name of the skustatuscode in the database.
	Table = "sku_status_code"
	// ActionTable is the table the holds the action relation/edge.
	ActionTable = "sku_status_code"
	// ActionInverseTable is the table name for the SkuAction entity.
	// It exists in this package in order to avoid circular dependency with the "skuaction" package.
	ActionInverseTable = "sku_action"
	// ActionColumn is the table column denoting the action relation/edge.
	ActionColumn = "sku_action_id"
)

// Columns holds all SQL columns for skustatuscode fields.
var Columns = []string{
	FieldID,
	FieldInsuranceCode,
	FieldReflectCode,
	FieldStatus,
	FieldCreateAt,
	FieldUpdateAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the SkuStatusCode type.
var ForeignKeys = []string{
	"sku_action_id",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateAt holds the default value on creation for the create_at field.
	DefaultCreateAt func() time.Time
	// DefaultUpdateAt holds the default value on creation for the update_at field.
	DefaultUpdateAt func() time.Time
	// UpdateDefaultUpdateAt holds the default value on update for the update_at field.
	UpdateDefaultUpdateAt func() time.Time
)
