// Code generated by entc, DO NOT EDIT.

package skustatuscode

import (
	"time"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/vgmdj/ddd-case/infrastructure/repository/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// InsuranceCode applies equality check predicate on the "insurance_code" field. It's identical to InsuranceCodeEQ.
func InsuranceCode(v string) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldInsuranceCode), v))
	})
}

// ReflectCode applies equality check predicate on the "reflect_code" field. It's identical to ReflectCodeEQ.
func ReflectCode(v string) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldReflectCode), v))
	})
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStatus), v))
	})
}

// CreateAt applies equality check predicate on the "create_at" field. It's identical to CreateAtEQ.
func CreateAt(v time.Time) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreateAt), v))
	})
}

// UpdateAt applies equality check predicate on the "update_at" field. It's identical to UpdateAtEQ.
func UpdateAt(v time.Time) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdateAt), v))
	})
}

// InsuranceCodeEQ applies the EQ predicate on the "insurance_code" field.
func InsuranceCodeEQ(v string) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldInsuranceCode), v))
	})
}

// InsuranceCodeNEQ applies the NEQ predicate on the "insurance_code" field.
func InsuranceCodeNEQ(v string) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldInsuranceCode), v))
	})
}

// InsuranceCodeIn applies the In predicate on the "insurance_code" field.
func InsuranceCodeIn(vs ...string) predicate.SkuStatusCode {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldInsuranceCode), v...))
	})
}

// InsuranceCodeNotIn applies the NotIn predicate on the "insurance_code" field.
func InsuranceCodeNotIn(vs ...string) predicate.SkuStatusCode {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldInsuranceCode), v...))
	})
}

// InsuranceCodeGT applies the GT predicate on the "insurance_code" field.
func InsuranceCodeGT(v string) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldInsuranceCode), v))
	})
}

// InsuranceCodeGTE applies the GTE predicate on the "insurance_code" field.
func InsuranceCodeGTE(v string) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldInsuranceCode), v))
	})
}

// InsuranceCodeLT applies the LT predicate on the "insurance_code" field.
func InsuranceCodeLT(v string) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldInsuranceCode), v))
	})
}

// InsuranceCodeLTE applies the LTE predicate on the "insurance_code" field.
func InsuranceCodeLTE(v string) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldInsuranceCode), v))
	})
}

// InsuranceCodeContains applies the Contains predicate on the "insurance_code" field.
func InsuranceCodeContains(v string) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldInsuranceCode), v))
	})
}

// InsuranceCodeHasPrefix applies the HasPrefix predicate on the "insurance_code" field.
func InsuranceCodeHasPrefix(v string) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldInsuranceCode), v))
	})
}

// InsuranceCodeHasSuffix applies the HasSuffix predicate on the "insurance_code" field.
func InsuranceCodeHasSuffix(v string) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldInsuranceCode), v))
	})
}

// InsuranceCodeEqualFold applies the EqualFold predicate on the "insurance_code" field.
func InsuranceCodeEqualFold(v string) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldInsuranceCode), v))
	})
}

// InsuranceCodeContainsFold applies the ContainsFold predicate on the "insurance_code" field.
func InsuranceCodeContainsFold(v string) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldInsuranceCode), v))
	})
}

// ReflectCodeEQ applies the EQ predicate on the "reflect_code" field.
func ReflectCodeEQ(v string) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldReflectCode), v))
	})
}

// ReflectCodeNEQ applies the NEQ predicate on the "reflect_code" field.
func ReflectCodeNEQ(v string) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldReflectCode), v))
	})
}

// ReflectCodeIn applies the In predicate on the "reflect_code" field.
func ReflectCodeIn(vs ...string) predicate.SkuStatusCode {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldReflectCode), v...))
	})
}

// ReflectCodeNotIn applies the NotIn predicate on the "reflect_code" field.
func ReflectCodeNotIn(vs ...string) predicate.SkuStatusCode {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldReflectCode), v...))
	})
}

// ReflectCodeGT applies the GT predicate on the "reflect_code" field.
func ReflectCodeGT(v string) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldReflectCode), v))
	})
}

// ReflectCodeGTE applies the GTE predicate on the "reflect_code" field.
func ReflectCodeGTE(v string) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldReflectCode), v))
	})
}

// ReflectCodeLT applies the LT predicate on the "reflect_code" field.
func ReflectCodeLT(v string) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldReflectCode), v))
	})
}

// ReflectCodeLTE applies the LTE predicate on the "reflect_code" field.
func ReflectCodeLTE(v string) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldReflectCode), v))
	})
}

// ReflectCodeContains applies the Contains predicate on the "reflect_code" field.
func ReflectCodeContains(v string) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldReflectCode), v))
	})
}

// ReflectCodeHasPrefix applies the HasPrefix predicate on the "reflect_code" field.
func ReflectCodeHasPrefix(v string) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldReflectCode), v))
	})
}

// ReflectCodeHasSuffix applies the HasSuffix predicate on the "reflect_code" field.
func ReflectCodeHasSuffix(v string) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldReflectCode), v))
	})
}

// ReflectCodeEqualFold applies the EqualFold predicate on the "reflect_code" field.
func ReflectCodeEqualFold(v string) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldReflectCode), v))
	})
}

// ReflectCodeContainsFold applies the ContainsFold predicate on the "reflect_code" field.
func ReflectCodeContainsFold(v string) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldReflectCode), v))
	})
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStatus), v))
	})
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStatus), v))
	})
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int) predicate.SkuStatusCode {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldStatus), v...))
	})
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int) predicate.SkuStatusCode {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldStatus), v...))
	})
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldStatus), v))
	})
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldStatus), v))
	})
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldStatus), v))
	})
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldStatus), v))
	})
}

// CreateAtEQ applies the EQ predicate on the "create_at" field.
func CreateAtEQ(v time.Time) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreateAt), v))
	})
}

// CreateAtNEQ applies the NEQ predicate on the "create_at" field.
func CreateAtNEQ(v time.Time) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreateAt), v))
	})
}

// CreateAtIn applies the In predicate on the "create_at" field.
func CreateAtIn(vs ...time.Time) predicate.SkuStatusCode {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCreateAt), v...))
	})
}

// CreateAtNotIn applies the NotIn predicate on the "create_at" field.
func CreateAtNotIn(vs ...time.Time) predicate.SkuStatusCode {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCreateAt), v...))
	})
}

// CreateAtGT applies the GT predicate on the "create_at" field.
func CreateAtGT(v time.Time) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreateAt), v))
	})
}

// CreateAtGTE applies the GTE predicate on the "create_at" field.
func CreateAtGTE(v time.Time) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreateAt), v))
	})
}

// CreateAtLT applies the LT predicate on the "create_at" field.
func CreateAtLT(v time.Time) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreateAt), v))
	})
}

// CreateAtLTE applies the LTE predicate on the "create_at" field.
func CreateAtLTE(v time.Time) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreateAt), v))
	})
}

// UpdateAtEQ applies the EQ predicate on the "update_at" field.
func UpdateAtEQ(v time.Time) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdateAt), v))
	})
}

// UpdateAtNEQ applies the NEQ predicate on the "update_at" field.
func UpdateAtNEQ(v time.Time) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdateAt), v))
	})
}

// UpdateAtIn applies the In predicate on the "update_at" field.
func UpdateAtIn(vs ...time.Time) predicate.SkuStatusCode {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldUpdateAt), v...))
	})
}

// UpdateAtNotIn applies the NotIn predicate on the "update_at" field.
func UpdateAtNotIn(vs ...time.Time) predicate.SkuStatusCode {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldUpdateAt), v...))
	})
}

// UpdateAtGT applies the GT predicate on the "update_at" field.
func UpdateAtGT(v time.Time) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdateAt), v))
	})
}

// UpdateAtGTE applies the GTE predicate on the "update_at" field.
func UpdateAtGTE(v time.Time) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdateAt), v))
	})
}

// UpdateAtLT applies the LT predicate on the "update_at" field.
func UpdateAtLT(v time.Time) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdateAt), v))
	})
}

// UpdateAtLTE applies the LTE predicate on the "update_at" field.
func UpdateAtLTE(v time.Time) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdateAt), v))
	})
}

// HasAction applies the HasEdge predicate on the "action" edge.
func HasAction() predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ActionTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ActionTable, ActionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasActionWith applies the HasEdge predicate on the "action" edge with a given conditions (other predicates).
func HasActionWith(preds ...predicate.SkuAction) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ActionInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ActionTable, ActionColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.SkuStatusCode) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.SkuStatusCode) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SkuStatusCode) predicate.SkuStatusCode {
	return predicate.SkuStatusCode(func(s *sql.Selector) {
		p(s.Not())
	})
}
